---
- name: Set up macOS CI runner
  hosts: macos
  remote_user: ec2-user

  tasks:
  - name: Install files in home directory
    ansible.builtin.copy:
      src: macos/{{ item }}
      dest: ~/{{ item }}
    loop:
      - .zshrc
      - .bashrc
      - .zshenv

  - name: Install Homebrew packages
    community.general.homebrew:
      name: "{{ item }}"
      state: present
    loop:
      - ruby
      - tmux
      - ninja
      - nvm
      - pyenv
      - cmake
      - node
      - ccache
      - pkg-config
      - glfw
      - bazelisk
      - fastlane

  - name: Install gems
    community.general.gem:
      name: jazzy
      user_install: false
      executable: /opt/homebrew/opt/ruby/bin/gem
    loop:
      - jazzy
      - xcpretty

  # https://github.com/ffi/ffi/issues/864
  - name: Install ffi gem, required for jazzy to function
    community.general.gem:
      name: ffi
      user_install: false
      build_flags: --enable-libffi-alloc
      executable: /opt/homebrew/opt/ruby/bin/gem

  - name: Create secrets directory if it does not exist
    ansible.builtin.file:
      path: ~/secrets
      state: directory

  - name: Copy secrets
    ansible.posix.synchronize:
      src: secrets/
      delete: true
      dest: ~/secrets
