# install these requirements using:
# ansible-galaxy install -r requirements.yml

---
collections:
- name: community.general

roles:
- name: monolithprojects.github_actions_runner
- name: geerlingguy.nodejs
- name: geerlingguy.swap
- name: dockpack.base_cmake