# To run this, a PERSONAL_ACCESS_TOKEN environment variable needs to be set
# https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

---
- name: Set up ARM64 Linux runner
  hosts: ubuntu
  become: yes
  vars:
    - github_account: maplibre
    - github_repo: maplibre-gl-native
    - runner_user: ubuntu
  roles:
    - role: monolithprojects.github_actions_runner
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: "18.x"
    - role: geerlingguy.swap
      vars:
        swap_file_size_mb: '2048'
    - { role: dockpack.base_cmake, cmake_version: "3.27", cmake_patch_version: "7", cmake_pkg_type: "linux-aarch64" }
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name:
        - git
        - ccache
        - cmake
        - ninja-build
        - pkg-config
        - xvfb
        - libcurl4-openssl-dev
        - libglfw3-dev
        - libuv1-dev
        - g++-10
        - libc++-9-dev
        - libc++abi-9-dev
        - ca-certificates
        - wget
        - libjpeg-dev
        - libpng-dev
        - libicu-dev
        - libjpeg-turbo8

